# ===================================================================
# Global Distributed Observability & Tracing Configuration
# ===================================================================
management.tracing.enabled=true



management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans

# Expose critical actuator management endpoints across the web fabric
management.endpoints.web.exposure.include=health,info,metrics,tracing