# ===================================================================
# Payment Service Application Infrastructure Definitions
# ===================================================================
spring.application.name=payment-service
server.port=8082

# ===================================================================
# Netflix Eureka Discovery Client Setup
# ===================================================================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}