spring.application.name=api-gateway-service
spring.config.import=optional:configserver:http://localhost:8888


# Tell the server to read from the dev branch instead of main/master
spring.cloud.config.label=dev_tanmay







# eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

