# Inside payment-service project locally (src/main/resources/application.properties)

spring.application.name=payment-service
spring.config.import=optional:configserver:http://localhost:8888


# eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Actuator
management.endpoints.web.exposure.include=health,info


# Tell the server to read from the dev branch instead of main/master
spring.cloud.config.label=dev_tanmay

