spring.application.name=eureka-server
server.port=8761


# eureka client configuration
# since this is registry itself , it should not register with other eureka

eureka.client.register-with-eureka=false
#disable registry downloading from another eureka server
eureka.client.fetch-registry=false

# eureka server configuration . Protects registered services from being removed too quickly during temporary network issues.
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000


management.endpoints.web.exposure.include=health,info
