server.port=8888
spring.application.name=config-server

# Connect to Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Point to your local Git repository folder containing properties files
spring.cloud.config.server.git.uri=file:/Users/ippo568/Desktop/MicroserviceDemo/config-repo

# Tell the server to read from the dev branch instead of main/master
spring.cloud.config.server.git.default-label=dev